### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by hhb19900618** [ifelseboyxx/xx_Notes#1]
设置这个  cell.fd_enforceFrameLayout = NO 有什么作用

**Comment by WithToken** [comment]
使用 `frameLayout`时 设置 `fd_enforceFrameLayout` 为 YES ，会根据 `layout` 模式来计算 `Cell` 的高度，并且在自定义 Cell 里重写 `sizeThatFit:` 方法。该属性默认为 `NO`。
